### ISSUE TITLE
运行第三步时出错！！

### ISSUE THREAD

**Issue by Ning030** [gitouni/Targetless-LiDAR-camera-calibration#5]
**在运行第三步时，按照您给的命令：**
`python multiway_reg.py --input_dir data/proc_pcd/`

**运行之后报错：**
并且在res_dir/work_dir中没有任何文件
```
Traceback (most recent call last):
  File "multiway_reg.py", line 217, in <module>
    pose_graph = full_registration(raw_pcd_list,pcd_feat_list,register,args.voxel_size,args.method)
  File "multiway_reg.py", line 162, in full_registration
    pcds[source_id], pcds[target_id],pcd_feats[source_id],pcd_feats[target_id],2*voxel,method)
  File "multiway_reg.py", line 117, in register_with_info
    self.method[method](src_pcd,dst_pcd,src_feat,dst_feat)
  File "multiway_reg.py", line 91, in ransac_register
    self.trans = ransac_register(src_pcd,dst_pcd,src_feat,dst_feat,icp_tuned=self.icp_tuned,seed=self.seed)
  File "/home/Targetless-LiDAR-camera-calibration/ransac.py", line 50, in register_with_feature
    ], o3d.pipelines.registration.RANSACConvergenceCriteria(max_iter, 0.999),seed=seed)
TypeError: registration_ransac_based_on_feature_matching(): incompatible function arguments. The following argument types are supported:
    1. (source: open3d.cuda.pybind.geometry.PointCloud, target: open3d.cuda.pybind.geometry.PointCloud, source_feature: open3d::pipelines::registration::Feature, target_feature: open3d::pipelines::registration::Feature, mutual_filter: bool, max_correspondence_distance: float, estimation_method: open3d.cuda.pybind.pipelines.registration.TransformationEstimation = TransformationEstimationPointToPoint without scaling., ransac_n: int = 3, checkers: List[open3d.cuda.pybind.pipelines.registration.CorrespondenceChecker] = [], criteria: open3d.cuda.pybind.pipelines.registration.RANSACConvergenceCriteria = RANSACConvergenceCriteria class with max_iteration=100000, and confidence=9.990000e-01) -> open3d.cuda.pybind.pipelines.registration.RegistrationResult

Invoked with: PointCloud with 10484 points., PointCloud with 11224 points., Feature class with dimension = 33 and num = 10484
Access its data via data member., Feature class with dimension = 33 and num = 11224
Access its data via data member., True, 0.6, TransformationEstimationPointToPoint without scaling., 3, [CorrespondenceCheckerBasedOnEdgeLength with similarity_threshold=0.900000, CorrespondenceCheckerBasedOnDistance with distance_threshold=0.300000], RANSACConvergenceCriteria class with max_iteration=100000, and confidence=9.990000e-01; kwargs: seed=None
```

**请问如何解决呢？**
另外，您的readme中拼写有错误，缺少字母i
`python multiway_reg.py --input_dr data/proc_pcd `

**Comment by gitouni** [comment]
看这个报错是你的open3d版本和我的不一样造成的，在你的环境中运行`pip show open3d`查看其版本，我的版本是0.15.2，如果版本太低，请升级到该版本，或者尝试去掉最后一个参数seed（但可能会每次运行结果不一致，PS：即使seed=0不同的设备运行出的结果也是不一样的）。
升级open3d:
```
pip install open3d --upgrade
```
或
```
pip install open3d==0.15.2
```

**Comment by Ning030** [comment]
非常感谢您的回答，现在可以跑通了！！
